"""ARTEMIS core models: agent status, model registry, audit log, compliance events."""
import uuid
from datetime import datetime
from sqlalchemy import String, Float, Integer, Boolean, DateTime, Text, JSON
from sqlalchemy.orm import Mapped, mapped_column
from .database import Base


def _uuid() -> str:
    return str(uuid.uuid4())


def _now() -> datetime:
    return datetime.utcnow()


class ArtemisAgentStatus(Base):
    """Live status of each ARTEMIS specialist agent."""
    __tablename__ = "artemis_agent_status"

    id: Mapped[str] = mapped_column(String(36), primary_key=True, default=_uuid)
    agent_key: Mapped[str] = mapped_column(String(50), nullable=False, unique=True, index=True)
    # trade | castrol | aviation | carbon
    agent_name: Mapped[str] = mapped_column(String(100), nullable=False)
    scope: Mapped[str] = mapped_column(String(200), nullable=False)
    # active | idle | error
    status: Mapped[str] = mapped_column(String(20), nullable=False, default="active", index=True)
    signals_today: Mapped[int] = mapped_column(Integer, nullable=False, default=0)
    last_signal_at: Mapped[datetime | None] = mapped_column(DateTime, nullable=True)
    primary_metric_value: Mapped[str | None] = mapped_column(String(50), nullable=True)
    primary_metric_label: Mapped[str | None] = mapped_column(String(50), nullable=True)
    updated_at: Mapped[datetime] = mapped_column(DateTime, default=_now, onupdate=_now)

    def __repr__(self) -> str:
        return f"<ArtemisAgentStatus {self.agent_key} {self.status}>"


class ArtemisModelRegistry(Base):
    """SageMaker model registry — tracks every ARTEMIS ML model in production."""
    __tablename__ = "artemis_model_registry"

    id: Mapped[str] = mapped_column(String(36), primary_key=True, default=_uuid)
    model_name: Mapped[str] = mapped_column(String(200), nullable=False, index=True)
    version: Mapped[str] = mapped_column(String(20), nullable=False)
    # validated | drift_detected | suspended | retraining
    status: Mapped[str] = mapped_column(String(30), nullable=False, default="validated", index=True)
    accuracy_pct: Mapped[float] = mapped_column(Float, nullable=False)
    # none | minimal | moderate | significant
    drift_status: Mapped[str] = mapped_column(String(20), nullable=False, default="none")
    next_review_days: Mapped[int] = mapped_column(Integer, nullable=False)
    agent_key: Mapped[str] = mapped_column(String(50), nullable=False, index=True)
    training_data_hash: Mapped[str | None] = mapped_column(String(64), nullable=True)
    last_validated_at: Mapped[datetime] = mapped_column(DateTime, default=_now)
    created_at: Mapped[datetime] = mapped_column(DateTime, default=_now)
    updated_at: Mapped[datetime] = mapped_column(DateTime, default=_now, onupdate=_now)

    def __repr__(self) -> str:
        return f"<ArtemisModelRegistry {self.model_name} v{self.version}>"


class ArtemisAuditLog(Base):
    """SOX-compliant immutable audit log for all ARTEMIS Tier 2 decisions."""
    __tablename__ = "artemis_audit_log"

    id: Mapped[str] = mapped_column(String(36), primary_key=True, default=_uuid)
    # recommendation_generated | human_approved | human_overridden | human_rejected | compliance_screened
    action_type: Mapped[str] = mapped_column(String(50), nullable=False, index=True)
    agent_key: Mapped[str] = mapped_column(String(50), nullable=False, index=True)
    model_id: Mapped[str | None] = mapped_column(String(36), nullable=True)
    recommendation_summary: Mapped[str | None] = mapped_column(Text, nullable=True)
    estimated_pnl_usd: Mapped[float | None] = mapped_column(Float, nullable=True)
    confidence_pct: Mapped[float | None] = mapped_column(Float, nullable=True)
    # tier_2 | tier_1
    regulatory_tier: Mapped[str] = mapped_column(String(10), nullable=False, default="tier_2")
    approver_id: Mapped[str | None] = mapped_column(String(100), nullable=True)
    override_rationale: Mapped[str | None] = mapped_column(Text, nullable=True)
    input_snapshot: Mapped[dict | None] = mapped_column(JSON, nullable=True)
    fca_supervisory_ref: Mapped[str | None] = mapped_column(String(100), nullable=True)
    created_at: Mapped[datetime] = mapped_column(DateTime, default=_now, index=True)
    # No updated_at — this record is immutable once written

    def __repr__(self) -> str:
        return f"<ArtemisAuditLog {self.action_type} {self.agent_key}>"


class ArtemisComplianceEvent(Base):
    """FCA/SOX/EU AI Act compliance events generated by the ARTEMIS governance rail."""
    __tablename__ = "artemis_compliance_events"

    id: Mapped[str] = mapped_column(String(36), primary_key=True, default=_uuid)
    # sox | fca | eu_ai_act | gdpr | model_drift | mar_alert
    framework: Mapped[str] = mapped_column(String(30), nullable=False, index=True)
    # compliant | warning | breach | resolved
    status: Mapped[str] = mapped_column(String(20), nullable=False, default="compliant", index=True)
    detail: Mapped[str] = mapped_column(Text, nullable=False)
    jurisdiction: Mapped[str | None] = mapped_column(String(50), nullable=True)
    agent_key: Mapped[str | None] = mapped_column(String(50), nullable=True)
    resolved_at: Mapped[datetime | None] = mapped_column(DateTime, nullable=True)
    created_at: Mapped[datetime] = mapped_column(DateTime, default=_now, index=True)
    updated_at: Mapped[datetime] = mapped_column(DateTime, default=_now, onupdate=_now)

    def __repr__(self) -> str:
        return f"<ArtemisComplianceEvent {self.framework} {self.status}>"
