"""initial_schema

Revision ID: 395e40c0974f
Revises: 
Create Date: 2026-04-13 05:28:43.851079

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '395e40c0974f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('adoption_barriers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('theme', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('vote_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('blend_specifications',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('grade_name', sa.String(length=80), nullable=False),
    sa.Column('viscosity_target', sa.Float(), nullable=False),
    sa.Column('viscosity_tol_low', sa.Float(), nullable=False),
    sa.Column('viscosity_tol_high', sa.Float(), nullable=False),
    sa.Column('pour_point_target', sa.Float(), nullable=False),
    sa.Column('tbn_target', sa.Float(), nullable=False),
    sa.Column('density_target', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('grade_name')
    )
    op.create_table('compliance_standards',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('jurisdiction', sa.String(length=80), nullable=True),
    sa.Column('standard_body', sa.String(length=80), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('implementation_waves',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('wave_number', sa.Integer(), nullable=False),
    sa.Column('wave_name', sa.String(length=120), nullable=False),
    sa.Column('period_start', sa.DateTime(), nullable=False),
    sa.Column('period_end', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('pct_complete', sa.Float(), nullable=False),
    sa.Column('budget_usd', sa.Float(), nullable=False),
    sa.Column('actual_spent_usd', sa.Float(), nullable=False),
    sa.Column('forecast_usd', sa.Float(), nullable=True),
    sa.Column('sites_in_scope', sa.JSON(), nullable=True),
    sa.Column('modules', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('wave_number')
    )
    op.create_index(op.f('ix_implementation_waves_status'), 'implementation_waves', ['status'], unique=False)
    op.create_table('ml_models',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('model_code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('model_type', sa.String(length=60), nullable=False),
    sa.Column('version', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('trained_on', sa.DateTime(), nullable=False),
    sa.Column('accuracy', sa.Float(), nullable=False),
    sa.Column('precision', sa.Float(), nullable=True),
    sa.Column('recall', sa.Float(), nullable=True),
    sa.Column('f1_score', sa.Float(), nullable=True),
    sa.Column('training_samples', sa.Integer(), nullable=True),
    sa.Column('assets_monitored', sa.Integer(), nullable=True),
    sa.Column('drift_status', sa.String(length=20), nullable=False),
    sa.Column('approval_status', sa.String(length=20), nullable=False),
    sa.Column('is_champion', sa.Boolean(), nullable=False),
    sa.Column('approved_by', sa.String(length=36), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('model_code')
    )
    op.create_index(op.f('ix_ml_models_status'), 'ml_models', ['status'], unique=False)
    op.create_table('offshore_platforms',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('field_name', sa.String(length=80), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('production_bopd', sa.Float(), nullable=False),
    sa.Column('uptime_pct', sa.Float(), nullable=False),
    sa.Column('active_wells', sa.Integer(), nullable=False),
    sa.Column('crew_count', sa.Integer(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('regulatory_changes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('effective_date', sa.DateTime(), nullable=False),
    sa.Column('regulation_code', sa.String(length=40), nullable=False),
    sa.Column('change_description', sa.Text(), nullable=False),
    sa.Column('impact_assessment', sa.Text(), nullable=True),
    sa.Column('internal_actions', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('roi_contributions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('source', sa.String(length=80), nullable=False),
    sa.Column('value_usd', sa.Float(), nullable=False),
    sa.Column('valuation_date', sa.DateTime(), nullable=False),
    sa.Column('methodology_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('schema_normalization_log',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('action_type', sa.String(length=40), nullable=False),
    sa.Column('target_tags', sa.JSON(), nullable=True),
    sa.Column('detail', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('applied_at', sa.DateTime(), nullable=False),
    sa.Column('applied_by_user_id', sa.String(length=36), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sites',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('country', sa.String(length=80), nullable=False),
    sa.Column('region', sa.String(length=80), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('refinery_type', sa.String(length=80), nullable=True),
    sa.Column('capacity_kbpd', sa.Float(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('name')
    )
    op.create_table('spare_parts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('part_number', sa.String(length=60), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('equipment_types', sa.JSON(), nullable=True),
    sa.Column('unit_cost', sa.Float(), nullable=False),
    sa.Column('supplier', sa.String(length=120), nullable=True),
    sa.Column('lead_time_days', sa.Integer(), nullable=False),
    sa.Column('criticality_score', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_spare_parts_part_number'), 'spare_parts', ['part_number'], unique=True)
    op.create_table('training_modules',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('module_type', sa.String(length=20), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('due_date', sa.DateTime(), nullable=True),
    sa.Column('estimated_duration_hours', sa.Float(), nullable=False),
    sa.Column('target_completion_pct', sa.Float(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('adoption_metrics',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('site_id', sa.String(length=36), nullable=False),
    sa.Column('metric_date', sa.DateTime(), nullable=False),
    sa.Column('total_users', sa.Integer(), nullable=False),
    sa.Column('active_users', sa.Integer(), nullable=False),
    sa.Column('avg_response_time_min', sa.Float(), nullable=False),
    sa.Column('avg_alert_action_rate_pct', sa.Float(), nullable=False),
    sa.Column('training_completion_rate_pct', sa.Float(), nullable=False),
    sa.Column('adoption_score', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_adoption_metrics_metric_date'), 'adoption_metrics', ['metric_date'], unique=False)
    op.create_index(op.f('ix_adoption_metrics_site_id'), 'adoption_metrics', ['site_id'], unique=False)
    op.create_table('blend_runs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('batch_code', sa.String(length=30), nullable=False),
    sa.Column('grade_name', sa.String(length=80), nullable=False),
    sa.Column('site_id', sa.String(length=36), nullable=False),
    sa.Column('tank_id', sa.String(length=30), nullable=True),
    sa.Column('target_volume_liters', sa.Float(), nullable=False),
    sa.Column('progress_pct', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_blend_runs_batch_code'), 'blend_runs', ['batch_code'], unique=True)
    op.create_index(op.f('ix_blend_runs_site_id'), 'blend_runs', ['site_id'], unique=False)
    op.create_index(op.f('ix_blend_runs_status'), 'blend_runs', ['status'], unique=False)
    op.create_table('budget_actuals',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('site_id', sa.String(length=36), nullable=False),
    sa.Column('period_month', sa.String(length=7), nullable=False),
    sa.Column('budgeted_usd', sa.Float(), nullable=False),
    sa.Column('actual_usd', sa.Float(), nullable=False),
    sa.Column('variance_usd', sa.Float(), nullable=False),
    sa.Column('cost_category', sa.String(length=60), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_budget_actuals_site_id'), 'budget_actuals', ['site_id'], unique=False)
    op.create_table('compliance_actions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('standard_id', sa.String(length=36), nullable=True),
    sa.Column('site_id', sa.String(length=36), nullable=True),
    sa.Column('action_description', sa.Text(), nullable=False),
    sa.Column('due_date', sa.DateTime(), nullable=True),
    sa.Column('owner', sa.String(length=120), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('ai_generated', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.ForeignKeyConstraint(['standard_id'], ['compliance_standards.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('compliance_audits',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('standard_id', sa.String(length=36), nullable=False),
    sa.Column('site_id', sa.String(length=36), nullable=False),
    sa.Column('audit_date', sa.DateTime(), nullable=False),
    sa.Column('next_audit_date', sa.DateTime(), nullable=True),
    sa.Column('inspector_name', sa.String(length=120), nullable=True),
    sa.Column('inspector_id', sa.String(length=36), nullable=True),
    sa.Column('score_pct', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('findings', sa.JSON(), nullable=True),
    sa.Column('days_until_due', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.ForeignKeyConstraint(['standard_id'], ['compliance_standards.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_compliance_audits_site_id'), 'compliance_audits', ['site_id'], unique=False)
    op.create_index(op.f('ix_compliance_audits_standard_id'), 'compliance_audits', ['standard_id'], unique=False)
    op.create_index(op.f('ix_compliance_audits_status'), 'compliance_audits', ['status'], unique=False)
    op.create_table('contractors',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('company_name', sa.String(length=120), nullable=False),
    sa.Column('specialty', sa.String(length=80), nullable=False),
    sa.Column('site_id', sa.String(length=36), nullable=True),
    sa.Column('crew_size', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('availability_from', sa.DateTime(), nullable=True),
    sa.Column('availability_to', sa.DateTime(), nullable=True),
    sa.Column('contact_name', sa.String(length=120), nullable=True),
    sa.Column('contact_email', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('crew_members',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=80), nullable=False),
    sa.Column('site_id', sa.String(length=36), nullable=True),
    sa.Column('availability', sa.String(length=20), nullable=False),
    sa.Column('skills', sa.JSON(), nullable=True),
    sa.Column('contractor_company', sa.String(length=120), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('edge_nodes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('node_code', sa.String(length=20), nullable=False),
    sa.Column('site_id', sa.String(length=36), nullable=False),
    sa.Column('hardware_spec', sa.String(length=120), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('inference_offload_pct', sa.Float(), nullable=False),
    sa.Column('avg_latency_ms', sa.Float(), nullable=False),
    sa.Column('cpu_usage_pct', sa.Float(), nullable=True),
    sa.Column('memory_usage_pct', sa.Float(), nullable=True),
    sa.Column('disk_usage_pct', sa.Float(), nullable=True),
    sa.Column('installed_at', sa.DateTime(), nullable=True),
    sa.Column('last_sync_at', sa.DateTime(), nullable=True),
    sa.Column('last_sync_label', sa.String(length=30), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_edge_nodes_node_code'), 'edge_nodes', ['node_code'], unique=True)
    op.create_index(op.f('ix_edge_nodes_site_id'), 'edge_nodes', ['site_id'], unique=False)
    op.create_index(op.f('ix_edge_nodes_status'), 'edge_nodes', ['status'], unique=False)
    op.create_table('energy_readings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('site_id', sa.String(length=36), nullable=False),
    sa.Column('reading_date', sa.DateTime(), nullable=False),
    sa.Column('total_energy_gj', sa.Float(), nullable=False),
    sa.Column('throughput_tonnes', sa.Float(), nullable=False),
    sa.Column('energy_intensity_gj_per_t', sa.Float(), nullable=False),
    sa.Column('power_mw', sa.Float(), nullable=True),
    sa.Column('steam_t_per_h', sa.Float(), nullable=True),
    sa.Column('co2_tonnes', sa.Float(), nullable=True),
    sa.Column('co2_intensity_per_tonne', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_energy_readings_reading_date'), 'energy_readings', ['reading_date'], unique=False)
    op.create_index(op.f('ix_energy_readings_site_id'), 'energy_readings', ['site_id'], unique=False)
    op.create_table('energy_saving_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('site_id', sa.String(length=36), nullable=False),
    sa.Column('event_date', sa.DateTime(), nullable=False),
    sa.Column('cost_avoided_usd', sa.Float(), nullable=False),
    sa.Column('source', sa.String(length=60), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_energy_saving_events_site_id'), 'energy_saving_events', ['site_id'], unique=False)
    op.create_table('energy_targets',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('site_id', sa.String(length=36), nullable=False),
    sa.Column('fiscal_year', sa.Integer(), nullable=False),
    sa.Column('target_gj_per_t', sa.Float(), nullable=False),
    sa.Column('target_co2_per_t', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_energy_targets_site_id'), 'energy_targets', ['site_id'], unique=False)
    op.create_table('equipment',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tag', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('equipment_type', sa.String(length=80), nullable=False),
    sa.Column('site_id', sa.String(length=36), nullable=False),
    sa.Column('manufacturer', sa.String(length=120), nullable=True),
    sa.Column('model_number', sa.String(length=120), nullable=True),
    sa.Column('installation_date', sa.DateTime(), nullable=True),
    sa.Column('design_life_years', sa.Integer(), nullable=True),
    sa.Column('health_score', sa.Float(), nullable=False),
    sa.Column('rul_hours', sa.Float(), nullable=True),
    sa.Column('ai_status', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('extra', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_equipment_site_id'), 'equipment', ['site_id'], unique=False)
    op.create_index(op.f('ix_equipment_tag'), 'equipment', ['tag'], unique=False)
    op.create_table('kpi_snapshots',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('site_id', sa.String(length=36), nullable=True),
    sa.Column('scope', sa.String(length=10), nullable=False),
    sa.Column('snapshot_date', sa.DateTime(), nullable=False),
    sa.Column('mtbf_hours', sa.Float(), nullable=True),
    sa.Column('mttr_hours', sa.Float(), nullable=True),
    sa.Column('oee_pct', sa.Float(), nullable=True),
    sa.Column('availability_pct', sa.Float(), nullable=True),
    sa.Column('performance_pct', sa.Float(), nullable=True),
    sa.Column('quality_pct', sa.Float(), nullable=True),
    sa.Column('alerts_actioned', sa.Integer(), nullable=True),
    sa.Column('model_accuracy_pct', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_kpi_snapshots_site_id'), 'kpi_snapshots', ['site_id'], unique=False)
    op.create_index(op.f('ix_kpi_snapshots_snapshot_date'), 'kpi_snapshots', ['snapshot_date'], unique=False)
    op.create_table('model_drift_metrics',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('model_id', sa.String(length=36), nullable=False),
    sa.Column('measured_at', sa.DateTime(), nullable=False),
    sa.Column('feature_drift_score', sa.Float(), nullable=False),
    sa.Column('concept_drift_score', sa.Float(), nullable=False),
    sa.Column('psi_score', sa.Float(), nullable=False),
    sa.Column('alert_level', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['model_id'], ['ml_models.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_model_drift_metrics_model_id'), 'model_drift_metrics', ['model_id'], unique=False)
    op.create_table('ot_data_sources',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('source_code', sa.String(length=30), nullable=False),
    sa.Column('source_type', sa.String(length=30), nullable=False),
    sa.Column('site_id', sa.String(length=36), nullable=False),
    sa.Column('tag_count', sa.Integer(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('quality_score_pct', sa.Float(), nullable=False),
    sa.Column('last_poll_at', sa.DateTime(), nullable=True),
    sa.Column('connection_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_code')
    )
    op.create_index(op.f('ix_ot_data_sources_site_id'), 'ot_data_sources', ['site_id'], unique=False)
    op.create_index(op.f('ix_ot_data_sources_status'), 'ot_data_sources', ['status'], unique=False)
    op.create_table('procurement_orders',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('po_number', sa.String(length=40), nullable=False),
    sa.Column('part_id', sa.String(length=36), nullable=False),
    sa.Column('site_id', sa.String(length=36), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_cost', sa.Float(), nullable=False),
    sa.Column('total_cost', sa.Float(), nullable=False),
    sa.Column('ordered_date', sa.DateTime(), nullable=False),
    sa.Column('expected_delivery', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('urgency_days', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['part_id'], ['spare_parts.id'], ),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('po_number')
    )
    op.create_index(op.f('ix_procurement_orders_part_id'), 'procurement_orders', ['part_id'], unique=False)
    op.create_table('retraining_runs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('model_id', sa.String(length=36), nullable=False),
    sa.Column('trigger', sa.String(length=80), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('new_accuracy', sa.Float(), nullable=True),
    sa.Column('new_f1', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('changelog', sa.Text(), nullable=True),
    sa.Column('training_samples_used', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['model_id'], ['ml_models.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_retraining_runs_model_id'), 'retraining_runs', ['model_id'], unique=False)
    op.create_table('shap_feature_importance',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('model_id', sa.String(length=36), nullable=False),
    sa.Column('feature_name', sa.String(length=120), nullable=False),
    sa.Column('importance_score', sa.Float(), nullable=False),
    sa.Column('direction', sa.String(length=20), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['model_id'], ['ml_models.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shap_feature_importance_model_id'), 'shap_feature_importance', ['model_id'], unique=False)
    op.create_table('spare_parts_stock',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('part_id', sa.String(length=36), nullable=False),
    sa.Column('site_id', sa.String(length=36), nullable=False),
    sa.Column('on_hand_qty', sa.Integer(), nullable=False),
    sa.Column('min_qty', sa.Integer(), nullable=False),
    sa.Column('on_order_qty', sa.Integer(), nullable=False),
    sa.Column('reorder_qty', sa.Integer(), nullable=False),
    sa.Column('last_updated', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['part_id'], ['spare_parts.id'], ),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_spare_parts_stock_part_id'), 'spare_parts_stock', ['part_id'], unique=False)
    op.create_index(op.f('ix_spare_parts_stock_site_id'), 'spare_parts_stock', ['site_id'], unique=False)
    op.create_table('subsea_alerts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('platform_id', sa.String(length=36), nullable=False),
    sa.Column('asset_name', sa.String(length=120), nullable=False),
    sa.Column('asset_type', sa.String(length=40), nullable=False),
    sa.Column('issue_description', sa.Text(), nullable=False),
    sa.Column('failure_probability_pct', sa.Float(), nullable=False),
    sa.Column('eta_days', sa.Float(), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['platform_id'], ['offshore_platforms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subsea_alerts_platform_id'), 'subsea_alerts', ['platform_id'], unique=False)
    op.create_index(op.f('ix_subsea_alerts_severity'), 'subsea_alerts', ['severity'], unique=False)
    op.create_table('turnaround_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tar_code', sa.String(length=20), nullable=False),
    sa.Column('site_id', sa.String(length=36), nullable=False),
    sa.Column('unit_name', sa.String(length=120), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=False),
    sa.Column('duration_days', sa.Integer(), nullable=False),
    sa.Column('budget_usd', sa.Float(), nullable=False),
    sa.Column('actual_cost_usd', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('work_scope_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tar_code')
    )
    op.create_index(op.f('ix_turnaround_events_site_id'), 'turnaround_events', ['site_id'], unique=False)
    op.create_index(op.f('ix_turnaround_events_status'), 'turnaround_events', ['status'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=40), nullable=False),
    sa.Column('site_id', sa.String(length=36), nullable=True),
    sa.Column('department', sa.String(length=120), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('vessel_schedules',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('vessel_name', sa.String(length=80), nullable=False),
    sa.Column('vessel_type', sa.String(length=30), nullable=False),
    sa.Column('platform_id', sa.String(length=36), nullable=False),
    sa.Column('departure_time', sa.DateTime(), nullable=False),
    sa.Column('arrival_time', sa.DateTime(), nullable=True),
    sa.Column('cargo_description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['platform_id'], ['offshore_platforms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vessel_schedules_platform_id'), 'vessel_schedules', ['platform_id'], unique=False)
    op.create_table('weather_forecasts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('platform_id', sa.String(length=36), nullable=False),
    sa.Column('forecast_date', sa.DateTime(), nullable=False),
    sa.Column('wave_height_m', sa.Float(), nullable=False),
    sa.Column('wind_speed_kt', sa.Float(), nullable=False),
    sa.Column('visibility_nm', sa.Float(), nullable=True),
    sa.Column('is_workable', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['platform_id'], ['offshore_platforms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_weather_forecasts_platform_id'), 'weather_forecasts', ['platform_id'], unique=False)
    op.create_table('well_integrity',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('platform_id', sa.String(length=36), nullable=False),
    sa.Column('well_name', sa.String(length=20), nullable=False),
    sa.Column('barrier_type', sa.String(length=40), nullable=False),
    sa.Column('annulus_pressure_bar', sa.Float(), nullable=True),
    sa.Column('last_test_date', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['platform_id'], ['offshore_platforms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_well_integrity_platform_id'), 'well_integrity', ['platform_id'], unique=False)
    op.create_table('active_learning_queue',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('model_id', sa.String(length=36), nullable=False),
    sa.Column('equipment_id', sa.String(length=36), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('sensor_snapshot', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('reviewer_id', sa.String(length=36), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('label', sa.String(length=40), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment.id'], ),
    sa.ForeignKeyConstraint(['model_id'], ['ml_models.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_active_learning_queue_model_id'), 'active_learning_queue', ['model_id'], unique=False)
    op.create_table('alerts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('alert_code', sa.String(length=20), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('equipment_id', sa.String(length=36), nullable=False),
    sa.Column('site_id', sa.String(length=36), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('failure_mode', sa.String(length=255), nullable=False),
    sa.Column('probability', sa.Float(), nullable=False),
    sa.Column('etf_days', sa.Float(), nullable=False),
    sa.Column('etf_min', sa.Float(), nullable=False),
    sa.Column('etf_max', sa.Float(), nullable=False),
    sa.Column('recommendation', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('is_push_sent', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment.id'], ),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alerts_alert_code'), 'alerts', ['alert_code'], unique=True)
    op.create_index(op.f('ix_alerts_created_at'), 'alerts', ['created_at'], unique=False)
    op.create_index(op.f('ix_alerts_equipment_id'), 'alerts', ['equipment_id'], unique=False)
    op.create_index(op.f('ix_alerts_severity'), 'alerts', ['severity'], unique=False)
    op.create_index(op.f('ix_alerts_site_id'), 'alerts', ['site_id'], unique=False)
    op.create_index(op.f('ix_alerts_status'), 'alerts', ['status'], unique=False)
    op.create_table('blend_quality_predictions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('blend_id', sa.String(length=36), nullable=False),
    sa.Column('predicted_at', sa.DateTime(), nullable=False),
    sa.Column('viscosity_predicted', sa.Float(), nullable=False),
    sa.Column('pour_point_predicted', sa.Float(), nullable=False),
    sa.Column('tbn_predicted', sa.Float(), nullable=False),
    sa.Column('confidence_low', sa.Float(), nullable=True),
    sa.Column('confidence_high', sa.Float(), nullable=True),
    sa.Column('prediction_status', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['blend_id'], ['blend_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_blend_quality_predictions_blend_id'), 'blend_quality_predictions', ['blend_id'], unique=False)
    op.create_table('blend_sensor_readings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('blend_id', sa.String(length=36), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('temperature_c', sa.Float(), nullable=False),
    sa.Column('viscosity_cst', sa.Float(), nullable=False),
    sa.Column('density_kg_m3', sa.Float(), nullable=True),
    sa.Column('dosing_rate_kg_min', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['blend_id'], ['blend_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_blend_sensor_readings_blend_id'), 'blend_sensor_readings', ['blend_id'], unique=False)
    op.create_table('change_champions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('site_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.String(length=80), nullable=False),
    sa.Column('sessions_count', sa.Integer(), nullable=False),
    sa.Column('alerts_actioned_count', sa.Integer(), nullable=False),
    sa.Column('training_completion_pct', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('compliance_evidence',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('audit_id', sa.String(length=36), nullable=False),
    sa.Column('document_type', sa.String(length=80), nullable=False),
    sa.Column('document_name', sa.String(length=255), nullable=False),
    sa.Column('file_url', sa.String(length=512), nullable=True),
    sa.Column('uploaded_date', sa.DateTime(), nullable=False),
    sa.Column('uploaded_by_user_id', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['audit_id'], ['compliance_audits.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_compliance_evidence_audit_id'), 'compliance_evidence', ['audit_id'], unique=False)
    op.create_table('delivery_risks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('risk_code', sa.String(length=10), nullable=False),
    sa.Column('wave_id', sa.String(length=36), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('impact_description', sa.Text(), nullable=True),
    sa.Column('probability', sa.String(length=20), nullable=False),
    sa.Column('mitigation_plan', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('owner_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['wave_id'], ['implementation_waves.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_delivery_risks_wave_id'), 'delivery_risks', ['wave_id'], unique=False)
    op.create_table('digital_twin_assets',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('equipment_id', sa.String(length=36), nullable=False),
    sa.Column('twin_type', sa.String(length=60), nullable=False),
    sa.Column('fidelity', sa.String(length=20), nullable=False),
    sa.Column('last_sync', sa.String(length=30), nullable=False),
    sa.Column('last_sync_at', sa.DateTime(), nullable=True),
    sa.Column('sync_latency_ms', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('model_url', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_digital_twin_assets_equipment_id'), 'digital_twin_assets', ['equipment_id'], unique=True)
    op.create_table('edge_model_deployments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('model_id', sa.String(length=36), nullable=False),
    sa.Column('node_id', sa.String(length=36), nullable=False),
    sa.Column('model_version', sa.String(length=20), nullable=False),
    sa.Column('model_size_mb', sa.Float(), nullable=False),
    sa.Column('quantization_method', sa.String(length=40), nullable=True),
    sa.Column('deployment_status', sa.String(length=20), nullable=False),
    sa.Column('deployed_at', sa.DateTime(), nullable=False),
    sa.Column('last_inference_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['model_id'], ['ml_models.id'], ),
    sa.ForeignKeyConstraint(['node_id'], ['edge_nodes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_edge_model_deployments_model_id'), 'edge_model_deployments', ['model_id'], unique=False)
    op.create_index(op.f('ix_edge_model_deployments_node_id'), 'edge_model_deployments', ['node_id'], unique=False)
    op.create_table('inspection_routes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('route_code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('site_id', sa.String(length=36), nullable=False),
    sa.Column('asset_sequence', sa.JSON(), nullable=True),
    sa.Column('distance_km', sa.Float(), nullable=True),
    sa.Column('estimated_duration_min', sa.Integer(), nullable=True),
    sa.Column('inspector_id', sa.String(length=36), nullable=True),
    sa.Column('inspector_name', sa.String(length=120), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('scheduled_date', sa.DateTime(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['inspector_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('route_code')
    )
    op.create_index(op.f('ix_inspection_routes_site_id'), 'inspection_routes', ['site_id'], unique=False)
    op.create_index(op.f('ix_inspection_routes_status'), 'inspection_routes', ['status'], unique=False)
    op.create_table('latency_benchmarks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('scenario_description', sa.String(length=120), nullable=False),
    sa.Column('edge_latency_ms', sa.Float(), nullable=False),
    sa.Column('cloud_latency_ms', sa.Float(), nullable=False),
    sa.Column('latency_saving_pct', sa.Float(), nullable=False),
    sa.Column('benchmark_date', sa.DateTime(), nullable=False),
    sa.Column('node_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['node_id'], ['edge_nodes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lims_results',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('blend_id', sa.String(length=36), nullable=False),
    sa.Column('test_date', sa.DateTime(), nullable=False),
    sa.Column('viscosity_measured', sa.Float(), nullable=False),
    sa.Column('pour_point_measured', sa.Float(), nullable=False),
    sa.Column('tbn_measured', sa.Float(), nullable=False),
    sa.Column('water_content_ppm', sa.Float(), nullable=True),
    sa.Column('particle_count', sa.Float(), nullable=True),
    sa.Column('result_status', sa.String(length=10), nullable=False),
    sa.Column('rework_required', sa.Boolean(), nullable=False),
    sa.Column('lab_notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['blend_id'], ['blend_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lims_results_blend_id'), 'lims_results', ['blend_id'], unique=True)
    op.create_table('maintenance_schedule_recommendations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tar_id', sa.String(length=36), nullable=False),
    sa.Column('equipment_id', sa.String(length=36), nullable=True),
    sa.Column('recommended_action', sa.Text(), nullable=False),
    sa.Column('recommended_window', sa.String(length=80), nullable=False),
    sa.Column('risk_level', sa.String(length=20), nullable=False),
    sa.Column('constraints', sa.JSON(), nullable=True),
    sa.Column('ai_confidence_pct', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('accepted_by_user_id', sa.String(length=36), nullable=True),
    sa.Column('accepted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment.id'], ),
    sa.ForeignKeyConstraint(['tar_id'], ['turnaround_events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_maintenance_schedule_recommendations_tar_id'), 'maintenance_schedule_recommendations', ['tar_id'], unique=False)
    op.create_table('ot_quality_issues',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('source_id', sa.String(length=36), nullable=False),
    sa.Column('tag_name', sa.String(length=120), nullable=False),
    sa.Column('issue_type', sa.String(length=40), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('impact_on_models', sa.JSON(), nullable=True),
    sa.Column('resolution_status', sa.String(length=20), nullable=False),
    sa.Column('detected_at', sa.DateTime(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['source_id'], ['ot_data_sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ot_quality_issues_source_id'), 'ot_quality_issues', ['source_id'], unique=False)
    op.create_table('sensor_readings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('equipment_id', sa.String(length=36), nullable=False),
    sa.Column('tag_name', sa.String(length=120), nullable=False),
    sa.Column('sensor_type', sa.String(length=40), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('quality', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sensor_readings_equipment_id'), 'sensor_readings', ['equipment_id'], unique=False)
    op.create_index(op.f('ix_sensor_readings_tag_name'), 'sensor_readings', ['tag_name'], unique=False)
    op.create_index(op.f('ix_sensor_readings_timestamp'), 'sensor_readings', ['timestamp'], unique=False)
    op.create_table('tar_constraints',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tar_id', sa.String(length=36), nullable=False),
    sa.Column('constraint_type', sa.String(length=30), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('owner', sa.String(length=120), nullable=True),
    sa.Column('resolution_date', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tar_id'], ['turnaround_events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tar_constraints_tar_id'), 'tar_constraints', ['tar_id'], unique=False)
    op.create_table('tar_tasks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tar_id', sa.String(length=36), nullable=False),
    sa.Column('equipment_id', sa.String(length=36), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('estimated_hours', sa.Float(), nullable=True),
    sa.Column('estimated_cost', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment.id'], ),
    sa.ForeignKeyConstraint(['tar_id'], ['turnaround_events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tar_tasks_tar_id'), 'tar_tasks', ['tar_id'], unique=False)
    op.create_table('training_enrollments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('module_id', sa.String(length=36), nullable=False),
    sa.Column('enrolled_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('assessment_score_pct', sa.Float(), nullable=True),
    sa.Column('certification_earned', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['module_id'], ['training_modules.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_training_enrollments_module_id'), 'training_enrollments', ['module_id'], unique=False)
    op.create_index(op.f('ix_training_enrollments_user_id'), 'training_enrollments', ['user_id'], unique=False)
    op.create_table('wave_milestones',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('milestone_code', sa.String(length=10), nullable=False),
    sa.Column('wave_id', sa.String(length=36), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('due_date', sa.DateTime(), nullable=False),
    sa.Column('owner', sa.String(length=120), nullable=True),
    sa.Column('owner_id', sa.String(length=36), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('completion_date', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['wave_id'], ['implementation_waves.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wave_milestones_wave_id'), 'wave_milestones', ['wave_id'], unique=False)
    op.create_table('alert_analogues',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('alert_id', sa.String(length=36), nullable=False),
    sa.Column('site_name', sa.String(length=120), nullable=False),
    sa.Column('event_date', sa.String(length=20), nullable=False),
    sa.Column('outcome', sa.Text(), nullable=False),
    sa.Column('days_to_failure', sa.Integer(), nullable=False),
    sa.Column('match_score', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['alert_id'], ['alerts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alert_analogues_alert_id'), 'alert_analogues', ['alert_id'], unique=False)
    op.create_table('alert_decisions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('alert_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('decision', sa.String(length=20), nullable=False),
    sa.Column('reason_code', sa.Text(), nullable=True),
    sa.Column('modified_action', sa.String(length=40), nullable=True),
    sa.Column('modified_timing', sa.String(length=80), nullable=True),
    sa.Column('work_order_id', sa.String(length=36), nullable=True),
    sa.Column('wo_number', sa.String(length=30), nullable=True),
    sa.Column('decided_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['alert_id'], ['alerts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alert_decisions_alert_id'), 'alert_decisions', ['alert_id'], unique=True)
    op.create_index(op.f('ix_alert_decisions_decided_at'), 'alert_decisions', ['decided_at'], unique=False)
    op.create_table('alert_shap_signals',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('alert_id', sa.String(length=36), nullable=False),
    sa.Column('signal_name', sa.String(length=120), nullable=False),
    sa.Column('values', sa.JSON(), nullable=False),
    sa.Column('contribution', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['alert_id'], ['alerts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alert_shap_signals_alert_id'), 'alert_shap_signals', ['alert_id'], unique=False)
    op.create_table('audit_log',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('alert_id', sa.String(length=36), nullable=False),
    sa.Column('alert_title', sa.String(length=255), nullable=False),
    sa.Column('decision', sa.String(length=20), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('user_name', sa.String(length=255), nullable=False),
    sa.Column('reason_code', sa.Text(), nullable=True),
    sa.Column('wo_number', sa.String(length=30), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['alert_id'], ['alerts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_log_alert_id'), 'audit_log', ['alert_id'], unique=False)
    op.create_index(op.f('ix_audit_log_timestamp'), 'audit_log', ['timestamp'], unique=False)
    op.create_table('cost_saving_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('equipment_id', sa.String(length=36), nullable=True),
    sa.Column('site_id', sa.String(length=36), nullable=False),
    sa.Column('alert_id', sa.String(length=36), nullable=True),
    sa.Column('event_date', sa.DateTime(), nullable=False),
    sa.Column('cost_avoided_usd', sa.Float(), nullable=False),
    sa.Column('category', sa.String(length=40), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['alert_id'], ['alerts.id'], ),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment.id'], ),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cost_saving_events_site_id'), 'cost_saving_events', ['site_id'], unique=False)
    op.create_table('inspection_items',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('route_id', sa.String(length=36), nullable=False),
    sa.Column('equipment_id', sa.String(length=36), nullable=True),
    sa.Column('asset_tag', sa.String(length=40), nullable=False),
    sa.Column('check_description', sa.Text(), nullable=False),
    sa.Column('iso_standard', sa.String(length=60), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_completed', sa.Boolean(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('completed_by_id', sa.String(length=36), nullable=True),
    sa.Column('observation_notes', sa.Text(), nullable=True),
    sa.Column('pass_fail', sa.String(length=10), nullable=True),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment.id'], ),
    sa.ForeignKeyConstraint(['route_id'], ['inspection_routes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inspection_items_route_id'), 'inspection_items', ['route_id'], unique=False)
    op.create_table('model_feedback',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('model_id', sa.String(length=36), nullable=False),
    sa.Column('alert_id', sa.String(length=36), nullable=True),
    sa.Column('feedback_type', sa.String(length=30), nullable=False),
    sa.Column('provided_by_user_id', sa.String(length=36), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['alert_id'], ['alerts.id'], ),
    sa.ForeignKeyConstraint(['model_id'], ['ml_models.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_model_feedback_model_id'), 'model_feedback', ['model_id'], unique=False)
    op.create_table('operating_envelope_params',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('twin_id', sa.String(length=36), nullable=False),
    sa.Column('parameter_name', sa.String(length=80), nullable=False),
    sa.Column('current_value', sa.Float(), nullable=False),
    sa.Column('normal_range_low', sa.Float(), nullable=False),
    sa.Column('normal_range_high', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['twin_id'], ['digital_twin_assets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_operating_envelope_params_twin_id'), 'operating_envelope_params', ['twin_id'], unique=False)
    op.create_table('twin_scenarios',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('twin_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('parameter_changes', sa.JSON(), nullable=True),
    sa.Column('predicted_outcomes', sa.JSON(), nullable=True),
    sa.Column('rul_delta_hours', sa.Float(), nullable=True),
    sa.Column('impact', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['twin_id'], ['digital_twin_assets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_twin_scenarios_twin_id'), 'twin_scenarios', ['twin_id'], unique=False)
    op.create_table('work_orders',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('wo_number', sa.String(length=30), nullable=False),
    sa.Column('equipment_id', sa.String(length=36), nullable=False),
    sa.Column('site_id', sa.String(length=36), nullable=False),
    sa.Column('alert_id', sa.String(length=36), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('ai_generated', sa.Boolean(), nullable=False),
    sa.Column('cost_estimate', sa.Float(), nullable=True),
    sa.Column('cost_actual', sa.Float(), nullable=True),
    sa.Column('failure_cost_avoided', sa.Float(), nullable=True),
    sa.Column('due_date', sa.DateTime(), nullable=True),
    sa.Column('scheduled_start', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('oem_instructions', sa.JSON(), nullable=True),
    sa.Column('required_resources', sa.JSON(), nullable=True),
    sa.Column('estimated_duration_hours', sa.Float(), nullable=True),
    sa.Column('created_by_user_id', sa.String(length=36), nullable=True),
    sa.Column('approved_by_user_id', sa.String(length=36), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('s4hana_ready', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['alert_id'], ['alerts.id'], ),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment.id'], ),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_work_orders_equipment_id'), 'work_orders', ['equipment_id'], unique=False)
    op.create_index(op.f('ix_work_orders_priority'), 'work_orders', ['priority'], unique=False)
    op.create_index(op.f('ix_work_orders_site_id'), 'work_orders', ['site_id'], unique=False)
    op.create_index(op.f('ix_work_orders_status'), 'work_orders', ['status'], unique=False)
    op.create_index(op.f('ix_work_orders_wo_number'), 'work_orders', ['wo_number'], unique=True)
    op.create_table('crew_assignments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('crew_member_id', sa.String(length=36), nullable=False),
    sa.Column('work_order_id', sa.String(length=36), nullable=False),
    sa.Column('assigned_at', sa.DateTime(), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['crew_member_id'], ['crew_members.id'], ),
    sa.ForeignKeyConstraint(['work_order_id'], ['work_orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crew_assignments_crew_member_id'), 'crew_assignments', ['crew_member_id'], unique=False)
    op.create_index(op.f('ix_crew_assignments_work_order_id'), 'crew_assignments', ['work_order_id'], unique=False)
    op.create_table('sap_bapi_records',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('work_order_id', sa.String(length=36), nullable=False),
    sa.Column('record_type', sa.String(length=10), nullable=False),
    sa.Column('sap_reference_id', sa.String(length=60), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('asset_tag', sa.String(length=40), nullable=True),
    sa.Column('s4hana_ready', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['work_order_id'], ['work_orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sap_bapi_records_work_order_id'), 'sap_bapi_records', ['work_order_id'], unique=False)
    op.create_table('wo_parts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('work_order_id', sa.String(length=36), nullable=False),
    sa.Column('part_id', sa.String(length=36), nullable=True),
    sa.Column('part_number', sa.String(length=60), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_cost', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('required_by', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['part_id'], ['spare_parts.id'], ),
    sa.ForeignKeyConstraint(['work_order_id'], ['work_orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wo_parts_work_order_id'), 'wo_parts', ['work_order_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_wo_parts_work_order_id'), table_name='wo_parts')
    op.drop_table('wo_parts')
    op.drop_index(op.f('ix_sap_bapi_records_work_order_id'), table_name='sap_bapi_records')
    op.drop_table('sap_bapi_records')
    op.drop_index(op.f('ix_crew_assignments_work_order_id'), table_name='crew_assignments')
    op.drop_index(op.f('ix_crew_assignments_crew_member_id'), table_name='crew_assignments')
    op.drop_table('crew_assignments')
    op.drop_index(op.f('ix_work_orders_wo_number'), table_name='work_orders')
    op.drop_index(op.f('ix_work_orders_status'), table_name='work_orders')
    op.drop_index(op.f('ix_work_orders_site_id'), table_name='work_orders')
    op.drop_index(op.f('ix_work_orders_priority'), table_name='work_orders')
    op.drop_index(op.f('ix_work_orders_equipment_id'), table_name='work_orders')
    op.drop_table('work_orders')
    op.drop_index(op.f('ix_twin_scenarios_twin_id'), table_name='twin_scenarios')
    op.drop_table('twin_scenarios')
    op.drop_index(op.f('ix_operating_envelope_params_twin_id'), table_name='operating_envelope_params')
    op.drop_table('operating_envelope_params')
    op.drop_index(op.f('ix_model_feedback_model_id'), table_name='model_feedback')
    op.drop_table('model_feedback')
    op.drop_index(op.f('ix_inspection_items_route_id'), table_name='inspection_items')
    op.drop_table('inspection_items')
    op.drop_index(op.f('ix_cost_saving_events_site_id'), table_name='cost_saving_events')
    op.drop_table('cost_saving_events')
    op.drop_index(op.f('ix_audit_log_timestamp'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_alert_id'), table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_index(op.f('ix_alert_shap_signals_alert_id'), table_name='alert_shap_signals')
    op.drop_table('alert_shap_signals')
    op.drop_index(op.f('ix_alert_decisions_decided_at'), table_name='alert_decisions')
    op.drop_index(op.f('ix_alert_decisions_alert_id'), table_name='alert_decisions')
    op.drop_table('alert_decisions')
    op.drop_index(op.f('ix_alert_analogues_alert_id'), table_name='alert_analogues')
    op.drop_table('alert_analogues')
    op.drop_index(op.f('ix_wave_milestones_wave_id'), table_name='wave_milestones')
    op.drop_table('wave_milestones')
    op.drop_index(op.f('ix_training_enrollments_user_id'), table_name='training_enrollments')
    op.drop_index(op.f('ix_training_enrollments_module_id'), table_name='training_enrollments')
    op.drop_table('training_enrollments')
    op.drop_index(op.f('ix_tar_tasks_tar_id'), table_name='tar_tasks')
    op.drop_table('tar_tasks')
    op.drop_index(op.f('ix_tar_constraints_tar_id'), table_name='tar_constraints')
    op.drop_table('tar_constraints')
    op.drop_index(op.f('ix_sensor_readings_timestamp'), table_name='sensor_readings')
    op.drop_index(op.f('ix_sensor_readings_tag_name'), table_name='sensor_readings')
    op.drop_index(op.f('ix_sensor_readings_equipment_id'), table_name='sensor_readings')
    op.drop_table('sensor_readings')
    op.drop_index(op.f('ix_ot_quality_issues_source_id'), table_name='ot_quality_issues')
    op.drop_table('ot_quality_issues')
    op.drop_index(op.f('ix_maintenance_schedule_recommendations_tar_id'), table_name='maintenance_schedule_recommendations')
    op.drop_table('maintenance_schedule_recommendations')
    op.drop_index(op.f('ix_lims_results_blend_id'), table_name='lims_results')
    op.drop_table('lims_results')
    op.drop_table('latency_benchmarks')
    op.drop_index(op.f('ix_inspection_routes_status'), table_name='inspection_routes')
    op.drop_index(op.f('ix_inspection_routes_site_id'), table_name='inspection_routes')
    op.drop_table('inspection_routes')
    op.drop_index(op.f('ix_edge_model_deployments_node_id'), table_name='edge_model_deployments')
    op.drop_index(op.f('ix_edge_model_deployments_model_id'), table_name='edge_model_deployments')
    op.drop_table('edge_model_deployments')
    op.drop_index(op.f('ix_digital_twin_assets_equipment_id'), table_name='digital_twin_assets')
    op.drop_table('digital_twin_assets')
    op.drop_index(op.f('ix_delivery_risks_wave_id'), table_name='delivery_risks')
    op.drop_table('delivery_risks')
    op.drop_index(op.f('ix_compliance_evidence_audit_id'), table_name='compliance_evidence')
    op.drop_table('compliance_evidence')
    op.drop_table('change_champions')
    op.drop_index(op.f('ix_blend_sensor_readings_blend_id'), table_name='blend_sensor_readings')
    op.drop_table('blend_sensor_readings')
    op.drop_index(op.f('ix_blend_quality_predictions_blend_id'), table_name='blend_quality_predictions')
    op.drop_table('blend_quality_predictions')
    op.drop_index(op.f('ix_alerts_status'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_site_id'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_severity'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_equipment_id'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_created_at'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_alert_code'), table_name='alerts')
    op.drop_table('alerts')
    op.drop_index(op.f('ix_active_learning_queue_model_id'), table_name='active_learning_queue')
    op.drop_table('active_learning_queue')
    op.drop_index(op.f('ix_well_integrity_platform_id'), table_name='well_integrity')
    op.drop_table('well_integrity')
    op.drop_index(op.f('ix_weather_forecasts_platform_id'), table_name='weather_forecasts')
    op.drop_table('weather_forecasts')
    op.drop_index(op.f('ix_vessel_schedules_platform_id'), table_name='vessel_schedules')
    op.drop_table('vessel_schedules')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_turnaround_events_status'), table_name='turnaround_events')
    op.drop_index(op.f('ix_turnaround_events_site_id'), table_name='turnaround_events')
    op.drop_table('turnaround_events')
    op.drop_index(op.f('ix_subsea_alerts_severity'), table_name='subsea_alerts')
    op.drop_index(op.f('ix_subsea_alerts_platform_id'), table_name='subsea_alerts')
    op.drop_table('subsea_alerts')
    op.drop_index(op.f('ix_spare_parts_stock_site_id'), table_name='spare_parts_stock')
    op.drop_index(op.f('ix_spare_parts_stock_part_id'), table_name='spare_parts_stock')
    op.drop_table('spare_parts_stock')
    op.drop_index(op.f('ix_shap_feature_importance_model_id'), table_name='shap_feature_importance')
    op.drop_table('shap_feature_importance')
    op.drop_index(op.f('ix_retraining_runs_model_id'), table_name='retraining_runs')
    op.drop_table('retraining_runs')
    op.drop_index(op.f('ix_procurement_orders_part_id'), table_name='procurement_orders')
    op.drop_table('procurement_orders')
    op.drop_index(op.f('ix_ot_data_sources_status'), table_name='ot_data_sources')
    op.drop_index(op.f('ix_ot_data_sources_site_id'), table_name='ot_data_sources')
    op.drop_table('ot_data_sources')
    op.drop_index(op.f('ix_model_drift_metrics_model_id'), table_name='model_drift_metrics')
    op.drop_table('model_drift_metrics')
    op.drop_index(op.f('ix_kpi_snapshots_snapshot_date'), table_name='kpi_snapshots')
    op.drop_index(op.f('ix_kpi_snapshots_site_id'), table_name='kpi_snapshots')
    op.drop_table('kpi_snapshots')
    op.drop_index(op.f('ix_equipment_tag'), table_name='equipment')
    op.drop_index(op.f('ix_equipment_site_id'), table_name='equipment')
    op.drop_table('equipment')
    op.drop_index(op.f('ix_energy_targets_site_id'), table_name='energy_targets')
    op.drop_table('energy_targets')
    op.drop_index(op.f('ix_energy_saving_events_site_id'), table_name='energy_saving_events')
    op.drop_table('energy_saving_events')
    op.drop_index(op.f('ix_energy_readings_site_id'), table_name='energy_readings')
    op.drop_index(op.f('ix_energy_readings_reading_date'), table_name='energy_readings')
    op.drop_table('energy_readings')
    op.drop_index(op.f('ix_edge_nodes_status'), table_name='edge_nodes')
    op.drop_index(op.f('ix_edge_nodes_site_id'), table_name='edge_nodes')
    op.drop_index(op.f('ix_edge_nodes_node_code'), table_name='edge_nodes')
    op.drop_table('edge_nodes')
    op.drop_table('crew_members')
    op.drop_table('contractors')
    op.drop_index(op.f('ix_compliance_audits_status'), table_name='compliance_audits')
    op.drop_index(op.f('ix_compliance_audits_standard_id'), table_name='compliance_audits')
    op.drop_index(op.f('ix_compliance_audits_site_id'), table_name='compliance_audits')
    op.drop_table('compliance_audits')
    op.drop_table('compliance_actions')
    op.drop_index(op.f('ix_budget_actuals_site_id'), table_name='budget_actuals')
    op.drop_table('budget_actuals')
    op.drop_index(op.f('ix_blend_runs_status'), table_name='blend_runs')
    op.drop_index(op.f('ix_blend_runs_site_id'), table_name='blend_runs')
    op.drop_index(op.f('ix_blend_runs_batch_code'), table_name='blend_runs')
    op.drop_table('blend_runs')
    op.drop_index(op.f('ix_adoption_metrics_site_id'), table_name='adoption_metrics')
    op.drop_index(op.f('ix_adoption_metrics_metric_date'), table_name='adoption_metrics')
    op.drop_table('adoption_metrics')
    op.drop_table('training_modules')
    op.drop_index(op.f('ix_spare_parts_part_number'), table_name='spare_parts')
    op.drop_table('spare_parts')
    op.drop_table('sites')
    op.drop_table('schema_normalization_log')
    op.drop_table('roi_contributions')
    op.drop_table('regulatory_changes')
    op.drop_table('offshore_platforms')
    op.drop_index(op.f('ix_ml_models_status'), table_name='ml_models')
    op.drop_table('ml_models')
    op.drop_index(op.f('ix_implementation_waves_status'), table_name='implementation_waves')
    op.drop_table('implementation_waves')
    op.drop_table('compliance_standards')
    op.drop_table('blend_specifications')
    op.drop_table('adoption_barriers')
    # ### end Alembic commands ###
