"""add_artemis_tables

Revision ID: b1b2ed85ef1b
Revises: 395e40c0974f
Create Date: 2026-04-13 18:44:53.008044

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b1b2ed85ef1b'
down_revision: Union[str, None] = '395e40c0974f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('artemis_agent_status',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('agent_key', sa.String(length=50), nullable=False),
    sa.Column('agent_name', sa.String(length=100), nullable=False),
    sa.Column('scope', sa.String(length=200), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('signals_today', sa.Integer(), nullable=False),
    sa.Column('last_signal_at', sa.DateTime(), nullable=True),
    sa.Column('primary_metric_value', sa.String(length=50), nullable=True),
    sa.Column('primary_metric_label', sa.String(length=50), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_artemis_agent_status_agent_key'), 'artemis_agent_status', ['agent_key'], unique=True)
    op.create_index(op.f('ix_artemis_agent_status_status'), 'artemis_agent_status', ['status'], unique=False)
    op.create_table('artemis_arbitrage_metrics',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('metric_date', sa.DateTime(), nullable=False),
    sa.Column('spreads_monitored', sa.Integer(), nullable=False),
    sa.Column('opportunities_detected', sa.Integer(), nullable=False),
    sa.Column('opportunities_approved', sa.Integer(), nullable=False),
    sa.Column('opportunities_overridden', sa.Integer(), nullable=False),
    sa.Column('total_pnl_identified_usd', sa.Float(), nullable=False),
    sa.Column('total_pnl_realised_usd', sa.Float(), nullable=False),
    sa.Column('avg_signal_latency_seconds', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_artemis_arbitrage_metrics_metric_date'), 'artemis_arbitrage_metrics', ['metric_date'], unique=True)
    op.create_table('artemis_arbitrage_opportunities',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('spread_name', sa.String(length=200), nullable=False),
    sa.Column('spread_type', sa.String(length=50), nullable=False),
    sa.Column('leg_a', sa.String(length=100), nullable=False),
    sa.Column('leg_b', sa.String(length=100), nullable=False),
    sa.Column('current_level', sa.String(length=50), nullable=False),
    sa.Column('current_level_numeric', sa.Float(), nullable=False),
    sa.Column('percentile_rank', sa.Integer(), nullable=False),
    sa.Column('estimated_pnl_usd', sa.Float(), nullable=False),
    sa.Column('execution_window', sa.String(length=50), nullable=False),
    sa.Column('confidence_pct', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('regulatory_tier', sa.String(length=10), nullable=False),
    sa.Column('approved_by', sa.String(length=100), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('override_rationale', sa.Text(), nullable=True),
    sa.Column('realised_pnl_usd', sa.Float(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_artemis_arbitrage_opportunities_created_at'), 'artemis_arbitrage_opportunities', ['created_at'], unique=False)
    op.create_index(op.f('ix_artemis_arbitrage_opportunities_spread_name'), 'artemis_arbitrage_opportunities', ['spread_name'], unique=False)
    op.create_index(op.f('ix_artemis_arbitrage_opportunities_spread_type'), 'artemis_arbitrage_opportunities', ['spread_type'], unique=False)
    op.create_index(op.f('ix_artemis_arbitrage_opportunities_status'), 'artemis_arbitrage_opportunities', ['status'], unique=False)
    op.create_table('artemis_audit_log',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('action_type', sa.String(length=50), nullable=False),
    sa.Column('agent_key', sa.String(length=50), nullable=False),
    sa.Column('model_id', sa.String(length=36), nullable=True),
    sa.Column('recommendation_summary', sa.Text(), nullable=True),
    sa.Column('estimated_pnl_usd', sa.Float(), nullable=True),
    sa.Column('confidence_pct', sa.Float(), nullable=True),
    sa.Column('regulatory_tier', sa.String(length=10), nullable=False),
    sa.Column('approver_id', sa.String(length=100), nullable=True),
    sa.Column('override_rationale', sa.Text(), nullable=True),
    sa.Column('input_snapshot', sa.JSON(), nullable=True),
    sa.Column('fca_supervisory_ref', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_artemis_audit_log_action_type'), 'artemis_audit_log', ['action_type'], unique=False)
    op.create_index(op.f('ix_artemis_audit_log_agent_key'), 'artemis_audit_log', ['agent_key'], unique=False)
    op.create_index(op.f('ix_artemis_audit_log_created_at'), 'artemis_audit_log', ['created_at'], unique=False)
    op.create_table('artemis_aviation_airports',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('iata_code', sa.String(length=4), nullable=False),
    sa.Column('airport_name', sa.String(length=200), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('region', sa.String(length=50), nullable=False),
    sa.Column('primary_airlines', sa.Text(), nullable=True),
    sa.Column('bp_supply_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_artemis_aviation_airports_country'), 'artemis_aviation_airports', ['country'], unique=False)
    op.create_index(op.f('ix_artemis_aviation_airports_iata_code'), 'artemis_aviation_airports', ['iata_code'], unique=True)
    op.create_index(op.f('ix_artemis_aviation_airports_region'), 'artemis_aviation_airports', ['region'], unique=False)
    op.create_table('artemis_aviation_contracts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('airport_id', sa.String(length=36), nullable=False),
    sa.Column('iata_code', sa.String(length=4), nullable=False),
    sa.Column('airline', sa.String(length=200), nullable=False),
    sa.Column('contract_type', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('expiry_date', sa.DateTime(), nullable=False),
    sa.Column('days_to_renewal', sa.Integer(), nullable=False),
    sa.Column('annual_volume_ml', sa.Float(), nullable=True),
    sa.Column('contract_value_usd', sa.Float(), nullable=True),
    sa.Column('recommended_structure', sa.String(length=50), nullable=True),
    sa.Column('scenario_pessimistic_usd', sa.Float(), nullable=True),
    sa.Column('scenario_baseline_usd', sa.Float(), nullable=True),
    sa.Column('scenario_optimistic_usd', sa.Float(), nullable=True),
    sa.Column('pack_generated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_artemis_aviation_contracts_airport_id'), 'artemis_aviation_contracts', ['airport_id'], unique=False)
    op.create_index(op.f('ix_artemis_aviation_contracts_expiry_date'), 'artemis_aviation_contracts', ['expiry_date'], unique=False)
    op.create_index(op.f('ix_artemis_aviation_contracts_iata_code'), 'artemis_aviation_contracts', ['iata_code'], unique=False)
    op.create_index(op.f('ix_artemis_aviation_contracts_status'), 'artemis_aviation_contracts', ['status'], unique=False)
    op.create_table('artemis_aviation_forecasts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('airport_id', sa.String(length=36), nullable=False),
    sa.Column('iata_code', sa.String(length=4), nullable=False),
    sa.Column('forecast_date', sa.DateTime(), nullable=False),
    sa.Column('d30_actual_ml', sa.Float(), nullable=False),
    sa.Column('d30_display', sa.String(length=20), nullable=False),
    sa.Column('d90_forecast_ml', sa.Float(), nullable=False),
    sa.Column('d90_display', sa.String(length=20), nullable=False),
    sa.Column('d90_delta_pct', sa.Float(), nullable=False),
    sa.Column('d90_delta_display', sa.String(length=20), nullable=False),
    sa.Column('confidence_interval_pct', sa.Float(), nullable=False),
    sa.Column('model_mape_pct', sa.Float(), nullable=False),
    sa.Column('top_driver', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_artemis_aviation_forecasts_airport_id'), 'artemis_aviation_forecasts', ['airport_id'], unique=False)
    op.create_index(op.f('ix_artemis_aviation_forecasts_created_at'), 'artemis_aviation_forecasts', ['created_at'], unique=False)
    op.create_index(op.f('ix_artemis_aviation_forecasts_forecast_date'), 'artemis_aviation_forecasts', ['forecast_date'], unique=False)
    op.create_index(op.f('ix_artemis_aviation_forecasts_iata_code'), 'artemis_aviation_forecasts', ['iata_code'], unique=False)
    op.create_table('artemis_base_oil_prices',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('grade', sa.String(length=100), nullable=False),
    sa.Column('price_per_mt', sa.Float(), nullable=False),
    sa.Column('price_display', sa.String(length=30), nullable=False),
    sa.Column('change_pct', sa.Float(), nullable=False),
    sa.Column('change_display', sa.String(length=20), nullable=False),
    sa.Column('alert_status', sa.String(length=20), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('price_date', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_artemis_base_oil_prices_grade'), 'artemis_base_oil_prices', ['grade'], unique=False)
    op.create_index(op.f('ix_artemis_base_oil_prices_price_date'), 'artemis_base_oil_prices', ['price_date'], unique=False)
    op.create_table('artemis_carbon_positions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('credit_type', sa.String(length=100), nullable=False),
    sa.Column('credit_category', sa.String(length=30), nullable=False),
    sa.Column('vintage_year', sa.Integer(), nullable=True),
    sa.Column('holdings_tonnes', sa.Float(), nullable=False),
    sa.Column('holdings_display', sa.String(length=30), nullable=False),
    sa.Column('obligation_tonnes', sa.Float(), nullable=True),
    sa.Column('obligation_display', sa.String(length=30), nullable=False),
    sa.Column('net_position_tonnes', sa.Float(), nullable=False),
    sa.Column('net_position_display', sa.String(length=30), nullable=False),
    sa.Column('current_price', sa.Float(), nullable=False),
    sa.Column('price_display', sa.String(length=20), nullable=False),
    sa.Column('price_currency', sa.String(length=5), nullable=False),
    sa.Column('market_value_usd', sa.Float(), nullable=True),
    sa.Column('position_date', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_artemis_carbon_positions_credit_category'), 'artemis_carbon_positions', ['credit_category'], unique=False)
    op.create_index(op.f('ix_artemis_carbon_positions_credit_type'), 'artemis_carbon_positions', ['credit_type'], unique=True)
    op.create_index(op.f('ix_artemis_carbon_positions_position_date'), 'artemis_carbon_positions', ['position_date'], unique=False)
    op.create_table('artemis_carbon_recommendations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('credit_type', sa.String(length=100), nullable=False),
    sa.Column('action', sa.String(length=10), nullable=False),
    sa.Column('urgency', sa.String(length=10), nullable=False),
    sa.Column('quantity_tonnes', sa.Float(), nullable=True),
    sa.Column('target_price', sa.Float(), nullable=True),
    sa.Column('expected_cost_benefit_usd', sa.Float(), nullable=True),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('compliance_driver', sa.String(length=200), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('approved_by', sa.String(length=100), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('tcfd_category', sa.String(length=100), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_artemis_carbon_recommendations_action'), 'artemis_carbon_recommendations', ['action'], unique=False)
    op.create_index(op.f('ix_artemis_carbon_recommendations_created_at'), 'artemis_carbon_recommendations', ['created_at'], unique=False)
    op.create_index(op.f('ix_artemis_carbon_recommendations_credit_type'), 'artemis_carbon_recommendations', ['credit_type'], unique=False)
    op.create_index(op.f('ix_artemis_carbon_recommendations_status'), 'artemis_carbon_recommendations', ['status'], unique=False)
    op.create_table('artemis_castrol_pricing_recs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('sku_code', sa.String(length=100), nullable=False),
    sa.Column('sku_name', sa.String(length=200), nullable=False),
    sa.Column('segment', sa.String(length=100), nullable=False),
    sa.Column('geography', sa.String(length=100), nullable=False),
    sa.Column('current_price_per_litre', sa.Float(), nullable=False),
    sa.Column('recommended_price_per_litre', sa.Float(), nullable=False),
    sa.Column('current_display', sa.String(length=20), nullable=False),
    sa.Column('recommended_display', sa.String(length=20), nullable=False),
    sa.Column('margin_impact_pct', sa.Float(), nullable=False),
    sa.Column('margin_impact_display', sa.String(length=20), nullable=False),
    sa.Column('rec_status', sa.String(length=30), nullable=False),
    sa.Column('confidence_pct', sa.Float(), nullable=False),
    sa.Column('base_oil_grade', sa.String(length=100), nullable=True),
    sa.Column('competitor_benchmark', sa.String(length=50), nullable=True),
    sa.Column('salesforce_opportunity_id', sa.String(length=100), nullable=True),
    sa.Column('approved_by', sa.String(length=100), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('override_rationale', sa.Text(), nullable=True),
    sa.Column('is_intraday_update', sa.Boolean(), nullable=False),
    sa.Column('generated_at', sa.DateTime(), nullable=False),
    sa.Column('valid_until', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_artemis_castrol_pricing_recs_generated_at'), 'artemis_castrol_pricing_recs', ['generated_at'], unique=False)
    op.create_index(op.f('ix_artemis_castrol_pricing_recs_geography'), 'artemis_castrol_pricing_recs', ['geography'], unique=False)
    op.create_index(op.f('ix_artemis_castrol_pricing_recs_rec_status'), 'artemis_castrol_pricing_recs', ['rec_status'], unique=False)
    op.create_index(op.f('ix_artemis_castrol_pricing_recs_segment'), 'artemis_castrol_pricing_recs', ['segment'], unique=False)
    op.create_index(op.f('ix_artemis_castrol_pricing_recs_sku_code'), 'artemis_castrol_pricing_recs', ['sku_code'], unique=False)
    op.create_table('artemis_compliance_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('framework', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('detail', sa.Text(), nullable=False),
    sa.Column('jurisdiction', sa.String(length=50), nullable=True),
    sa.Column('agent_key', sa.String(length=50), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_artemis_compliance_events_created_at'), 'artemis_compliance_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_artemis_compliance_events_framework'), 'artemis_compliance_events', ['framework'], unique=False)
    op.create_index(op.f('ix_artemis_compliance_events_status'), 'artemis_compliance_events', ['status'], unique=False)
    op.create_table('artemis_model_registry',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('model_name', sa.String(length=200), nullable=False),
    sa.Column('version', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('accuracy_pct', sa.Float(), nullable=False),
    sa.Column('drift_status', sa.String(length=20), nullable=False),
    sa.Column('next_review_days', sa.Integer(), nullable=False),
    sa.Column('agent_key', sa.String(length=50), nullable=False),
    sa.Column('training_data_hash', sa.String(length=64), nullable=True),
    sa.Column('last_validated_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_artemis_model_registry_agent_key'), 'artemis_model_registry', ['agent_key'], unique=False)
    op.create_index(op.f('ix_artemis_model_registry_model_name'), 'artemis_model_registry', ['model_name'], unique=False)
    op.create_index(op.f('ix_artemis_model_registry_status'), 'artemis_model_registry', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_artemis_model_registry_status'), table_name='artemis_model_registry')
    op.drop_index(op.f('ix_artemis_model_registry_model_name'), table_name='artemis_model_registry')
    op.drop_index(op.f('ix_artemis_model_registry_agent_key'), table_name='artemis_model_registry')
    op.drop_table('artemis_model_registry')
    op.drop_index(op.f('ix_artemis_compliance_events_status'), table_name='artemis_compliance_events')
    op.drop_index(op.f('ix_artemis_compliance_events_framework'), table_name='artemis_compliance_events')
    op.drop_index(op.f('ix_artemis_compliance_events_created_at'), table_name='artemis_compliance_events')
    op.drop_table('artemis_compliance_events')
    op.drop_index(op.f('ix_artemis_castrol_pricing_recs_sku_code'), table_name='artemis_castrol_pricing_recs')
    op.drop_index(op.f('ix_artemis_castrol_pricing_recs_segment'), table_name='artemis_castrol_pricing_recs')
    op.drop_index(op.f('ix_artemis_castrol_pricing_recs_rec_status'), table_name='artemis_castrol_pricing_recs')
    op.drop_index(op.f('ix_artemis_castrol_pricing_recs_geography'), table_name='artemis_castrol_pricing_recs')
    op.drop_index(op.f('ix_artemis_castrol_pricing_recs_generated_at'), table_name='artemis_castrol_pricing_recs')
    op.drop_table('artemis_castrol_pricing_recs')
    op.drop_index(op.f('ix_artemis_carbon_recommendations_status'), table_name='artemis_carbon_recommendations')
    op.drop_index(op.f('ix_artemis_carbon_recommendations_credit_type'), table_name='artemis_carbon_recommendations')
    op.drop_index(op.f('ix_artemis_carbon_recommendations_created_at'), table_name='artemis_carbon_recommendations')
    op.drop_index(op.f('ix_artemis_carbon_recommendations_action'), table_name='artemis_carbon_recommendations')
    op.drop_table('artemis_carbon_recommendations')
    op.drop_index(op.f('ix_artemis_carbon_positions_position_date'), table_name='artemis_carbon_positions')
    op.drop_index(op.f('ix_artemis_carbon_positions_credit_type'), table_name='artemis_carbon_positions')
    op.drop_index(op.f('ix_artemis_carbon_positions_credit_category'), table_name='artemis_carbon_positions')
    op.drop_table('artemis_carbon_positions')
    op.drop_index(op.f('ix_artemis_base_oil_prices_price_date'), table_name='artemis_base_oil_prices')
    op.drop_index(op.f('ix_artemis_base_oil_prices_grade'), table_name='artemis_base_oil_prices')
    op.drop_table('artemis_base_oil_prices')
    op.drop_index(op.f('ix_artemis_aviation_forecasts_iata_code'), table_name='artemis_aviation_forecasts')
    op.drop_index(op.f('ix_artemis_aviation_forecasts_forecast_date'), table_name='artemis_aviation_forecasts')
    op.drop_index(op.f('ix_artemis_aviation_forecasts_created_at'), table_name='artemis_aviation_forecasts')
    op.drop_index(op.f('ix_artemis_aviation_forecasts_airport_id'), table_name='artemis_aviation_forecasts')
    op.drop_table('artemis_aviation_forecasts')
    op.drop_index(op.f('ix_artemis_aviation_contracts_status'), table_name='artemis_aviation_contracts')
    op.drop_index(op.f('ix_artemis_aviation_contracts_iata_code'), table_name='artemis_aviation_contracts')
    op.drop_index(op.f('ix_artemis_aviation_contracts_expiry_date'), table_name='artemis_aviation_contracts')
    op.drop_index(op.f('ix_artemis_aviation_contracts_airport_id'), table_name='artemis_aviation_contracts')
    op.drop_table('artemis_aviation_contracts')
    op.drop_index(op.f('ix_artemis_aviation_airports_region'), table_name='artemis_aviation_airports')
    op.drop_index(op.f('ix_artemis_aviation_airports_iata_code'), table_name='artemis_aviation_airports')
    op.drop_index(op.f('ix_artemis_aviation_airports_country'), table_name='artemis_aviation_airports')
    op.drop_table('artemis_aviation_airports')
    op.drop_index(op.f('ix_artemis_audit_log_created_at'), table_name='artemis_audit_log')
    op.drop_index(op.f('ix_artemis_audit_log_agent_key'), table_name='artemis_audit_log')
    op.drop_index(op.f('ix_artemis_audit_log_action_type'), table_name='artemis_audit_log')
    op.drop_table('artemis_audit_log')
    op.drop_index(op.f('ix_artemis_arbitrage_opportunities_status'), table_name='artemis_arbitrage_opportunities')
    op.drop_index(op.f('ix_artemis_arbitrage_opportunities_spread_type'), table_name='artemis_arbitrage_opportunities')
    op.drop_index(op.f('ix_artemis_arbitrage_opportunities_spread_name'), table_name='artemis_arbitrage_opportunities')
    op.drop_index(op.f('ix_artemis_arbitrage_opportunities_created_at'), table_name='artemis_arbitrage_opportunities')
    op.drop_table('artemis_arbitrage_opportunities')
    op.drop_index(op.f('ix_artemis_arbitrage_metrics_metric_date'), table_name='artemis_arbitrage_metrics')
    op.drop_table('artemis_arbitrage_metrics')
    op.drop_index(op.f('ix_artemis_agent_status_status'), table_name='artemis_agent_status')
    op.drop_index(op.f('ix_artemis_agent_status_agent_key'), table_name='artemis_agent_status')
    op.drop_table('artemis_agent_status')
    # ### end Alembic commands ###
